import { existsSync, readdirSync, readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve, relative } from "node:path";
import { parse as parseYaml } from "yaml";
import type { LoadedConfig } from "../config.ts";
import type { ScanCache } from "../commands/scan.ts";
import type { AuditContext, AuditRule, Finding, RuleResult, Severity } from "./types.ts";
import { handlers } from "./handlers.ts";
import { buildSources, formatFooter } from "../footer.ts";

export interface AuditResult {
  date: string;
  rules: RuleResult[];
  errors: Finding[];
  warnings: Finding[];
  inputs: string[];
}

export function loadRules(rulesDir: string): AuditRule[] {
  if (!existsSync(rulesDir)) return [];
  const entries = readdirSync(rulesDir, { withFileTypes: true });
  const rules: AuditRule[] = [];
  for (const ent of entries) {
    if (!ent.isFile() || !ent.name.endsWith(".yaml")) continue;
    const full = resolve(rulesDir, ent.name);
    const raw = readFileSync(full, "utf8");
    const parsed = parseYaml(raw) as Record<string, unknown>;
    rules.push({
      id: String(parsed.id ?? ent.name),
      name: String(parsed.name ?? parsed.id ?? ent.name),
      axiom_refs: Array.isArray(parsed.axiom_refs)
        ? (parsed.axiom_refs as unknown[]).filter((x): x is string => typeof x === "string")
        : [],
      severity: (parsed.severity === "ERROR" ? "ERROR" : "WARNING") as Severity,
      handler: String(parsed.handler ?? ""),
      enabled: parsed.enabled !== false,
      config: (parsed.config as Record<string, unknown>) ?? {},
      sourcePath: full,
    });
  }
  rules.sort((a, b) => a.id.localeCompare(b.id));
  return rules;
}

export async function runAudit(
  loaded: LoadedConfig,
  options: { only?: string[]; scanCache?: ScanCache | null } = {},
): Promise<AuditResult> {
  const rulesDir = resolve(
    loaded.workspaceRoot,
    loaded.config.orchestrator.audit_rules_dir,
  );
  const allRules = loadRules(rulesDir);
  const selected = options.only && options.only.length
    ? allRules.filter((r) => options.only!.includes(r.id))
    : allRules.filter((r) => r.enabled);

  const inputs = new Set<string>();
  const results: RuleResult[] = [];
  const errors: Finding[] = [];
  const warnings: Finding[] = [];
  const overrideRegenData: { ctx: AuditContext | null } = { ctx: null };

  for (const rule of selected) {
    inputs.add(rule.sourcePath);
    const handler = handlers[rule.handler];
    if (!handler) {
      results.push({
        ruleId: rule.id,
        ruleName: rule.name,
        severity: rule.severity,
        status: "error",
        findings: [],
        error: `no handler registered: '${rule.handler}'`,
      });
      continue;
    }
    const ctx: AuditContext = {
      loaded,
      rule,
      scanCache: options.scanCache ?? null,
      inputs,
    };
    try {
      const out = await handler(ctx);
      results.push({
        ruleId: rule.id,
        ruleName: rule.name,
        severity: rule.severity,
        status: "ok",
        findings: out,
      });
      for (const f of out) {
        if (f.severity === "ERROR") errors.push(f);
        else warnings.push(f);
      }
      if (rule.handler === "override-regen") overrideRegenData.ctx = ctx;
    } catch (err) {
      results.push({
        ruleId: rule.id,
        ruleName: rule.name,
        severity: rule.severity,
        status: "error",
        findings: [],
        error: (err as Error).message,
      });
    }
  }

  if (overrideRegenData.ctx) {
    writeOverridesDashboard(loaded, overrideRegenData.ctx);
  }

  const date = new Date().toISOString().slice(0, 10);
  return {
    date,
    rules: results,
    errors,
    warnings,
    inputs: [...inputs].filter((p) => !p.startsWith("__")),
  };
}

interface OverrideEntry {
  axiom: string;
  block: string;
  repo: string;
  justification: string;
}

function writeOverridesDashboard(loaded: LoadedConfig, ctx: AuditContext): void {
  const entries =
    ((ctx as unknown as { __overrides?: OverrideEntry[] }).__overrides) ?? [];
  const ownInputs =
    ((ctx as unknown as { __overrideInputs?: string[] }).__overrideInputs) ?? [];
  const outPath = resolve(loaded.workspaceRoot, loaded.config.governance.overrides_file);
  mkdirSync(dirname(outPath), { recursive: true });
  const lines: string[] = [];
  lines.push("# Axiom Override Dashboard");
  lines.push("");
  lines.push(
    "_DERIVED — regenerated by `governor audit` (rule 05 override-regen). " +
      "See `governance/overrides.canonical-snapshot.md` for the pre-Wave-2 hand-curated state._",
  );
  lines.push("");
  lines.push(`Active overrides: ${entries.length}.`);
  lines.push("");
  if (entries.length === 0) {
    lines.push("_No axiom overrides recorded in archived manifest frontmatter._");
  } else {
    const byAxiom = new Map<string, OverrideEntry[]>();
    for (const e of entries) {
      const k = e.axiom.replace(/-/g, "");
      const arr = byAxiom.get(k) ?? [];
      arr.push(e);
      byAxiom.set(k, arr);
    }
    for (const [axiom, arr] of [...byAxiom].sort(([a], [b]) => a.localeCompare(b))) {
      lines.push(`## ${axiom} (${arr.length})`);
      lines.push("");
      for (const e of arr) {
        lines.push(`- ${e.repo} ${e.block} — ${e.justification}`);
      }
      lines.push("");
    }
  }
  const footer = formatFooter({
    generator: "audit:override-regen",
    generatedAt: new Date().toISOString(),
    sources: buildSources(loaded.workspaceRoot, ownInputs),
  });
  writeFileSync(outPath, lines.join("\n") + "\n" + footer, "utf8");
}

export function renderAuditReport(
  loaded: LoadedConfig,
  result: AuditResult,
): string {
  const lines: string[] = [];
  lines.push(`# Governor Audit — ${result.date}`);
  lines.push("");
  lines.push("_OPERATIONAL — regenerate via `governor audit`._");
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(`- Errors: ${result.errors.length}`);
  lines.push(`- Warnings: ${result.warnings.length}`);
  lines.push(`- Rules executed: ${result.rules.length}`);
  lines.push(`- Files inspected: ${result.inputs.length}`);
  lines.push("");

  if (result.errors.length > 0) {
    lines.push("## Errors");
    lines.push("");
    appendFindings(lines, result.rules, "ERROR");
  }
  if (result.warnings.length > 0) {
    lines.push("## Warnings");
    lines.push("");
    appendFindings(lines, result.rules, "WARNING");
  }

  lines.push("## Rule status");
  lines.push("");
  lines.push("| Rule | Severity | Status | Findings |");
  lines.push("|------|----------|--------|----------|");
  for (const r of result.rules) {
    const status = r.status === "ok" ? "OK" : `ERROR (${r.error ?? ""})`;
    lines.push(
      `| ${r.ruleId} | ${r.severity} | ${status} | ${r.findings.length} |`,
    );
  }
  lines.push("");

  const footer = formatFooter({
    generator: "audit",
    generatedAt: new Date().toISOString(),
    sources: buildSources(loaded.workspaceRoot, result.inputs.slice(0, 200)),
  });
  return lines.join("\n") + "\n" + footer;
}

function appendFindings(
  lines: string[],
  results: RuleResult[],
  severity: Severity,
): void {
  for (const r of results) {
    const subset = r.findings.filter((f) => f.severity === severity);
    if (subset.length === 0) continue;
    lines.push(`### ${r.ruleId} — ${r.ruleName}`);
    for (const f of subset.slice(0, 100)) {
      const loc = f.path
        ? f.line
          ? ` (\`${f.path}:${f.line}\`)`
          : ` (\`${f.path}\`)`
        : "";
      lines.push(`- ${f.message}${loc}`);
    }
    if (subset.length > 100) {
      lines.push(`- _… ${subset.length - 100} more not shown_`);
    }
    lines.push("");
  }
}

export function summarize(result: AuditResult): string {
  return `${result.errors.length} error(s), ${result.warnings.length} warning(s), ${result.rules.length} rule(s) executed, ${result.inputs.length} file(s) inspected`;
}

export function relPath(loaded: LoadedConfig, abs: string): string {
  return relative(loaded.workspaceRoot, abs).replace(/\\/g, "/");
}
